// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AutoSaveTextToFile(arg1, arg2, arg3) {
  return window['go']['main']['App']['AutoSaveTextToFile'](arg1, arg2, arg3);
}

export function GetCachedCSI(arg1, arg2) {
  return window['go']['main']['App']['GetCachedCSI'](arg1, arg2);
}

export function Reconnect() {
  return window['go']['main']['App']['Reconnect']();
}

export function UpdateSerialConfig(arg1, arg2) {
  return window['go']['main']['App']['UpdateSerialConfig'](arg1, arg2);
}
