// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AutoSaveTextToFile(arg1, arg2, arg3) {
  return window['go']['main']['App']['AutoSaveTextToFile'](arg1, arg2, arg3);
}

export function ClearSavedData() {
  return window['go']['main']['App']['ClearSavedData']();
}

export function DeleteFile(arg1) {
  return window['go']['main']['App']['DeleteFile'](arg1);
}

export function GetCachedCSI(arg1, arg2) {
  return window['go']['main']['App']['GetCachedCSI'](arg1, arg2);
}

export function LoadFrameFile(arg1) {
  return window['go']['main']['App']['LoadFrameFile'](arg1);
}

export function ReadSavedDataFileName() {
  return window['go']['main']['App']['ReadSavedDataFileName']();
}

export function Reconnect() {
  return window['go']['main']['App']['Reconnect']();
}

export function SaveDataSegment(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['SaveDataSegment'](arg1, arg2, arg3, arg4);
}

export function UpdateSerialConfig(arg1, arg2) {
  return window['go']['main']['App']['UpdateSerialConfig'](arg1, arg2);
}
