// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function AutoSaveTextToFile(arg1:number,arg2:number,arg3:string):Promise<void>;

export function ClearSavedData():Promise<void>;

export function GetCachedCSI(arg1:number,arg2:number):Promise<Array<main.CSIFrame>>;

export function ReadSavedDataFileName():Promise<Array<string>>;

export function Reconnect():Promise<void>;

export function UpdateSerialConfig(arg1:string,arg2:number):Promise<void>;
